### ISSUE TITLE
Issue adding tslint in react-slingshot 

### ISSUE THREAD

**Issue by Rajiv-Kulkarni** [typescriptcrew/ts-react-slingshot#22]
When I add the tslint key to the webpack.config.dev.js like you have I get an error.
tslint: {
configFile: './tslint.json',
emitErrors: true,
failOnHint: true
},

However, I can add it to the module section like so without any issues:
{test: /.ts$/, enforce: 'pre', exclude: /node_modules/, loader: 'tslint-loader', options: {emitErrors: true, failOnHint: true, tsConfigFile: 'tsconfig.json'}},

Does that make sense? Also, my unit tests are in different folders under components in the src folder. However the tests did n't run and had to move to a folder tests I guess because of this line in the package.json:
"testRegex": "/tests/.*\.(ts|tsx|js)$"

How can I change it so it looks at the folders and subfolders under components?

Thirdly, I just need to add the tslint configuration to the webpack.config.dev.js, right and not the webpack.config.prod.js, right?

Thanks.

**Comment by nickytonline** [comment]
For tslint failing like my config, you'll have to show me in a repo you own.

For the tests, you can modify the regex to just look everywhere in the src folder, e.g. `"testRegex": "/src/.*\\.spec\\.(ts|tsx|js)$"`. You'll need to name your tests to distinguish them from regular ts and tsx files, so instead of `some-test.ts`, do `som-test.spec.ts`. Visually it'll be clearer to you as well when looking a the folder.

For the tslint configuration, I would add it in both, because you want your build to fail if linting fails.

**Comment by nickytonline** [comment]
Closing as no response from the issue opener. @Rajiv-Kulkarni, feel free to reopen this if the problem still persists.
